all: zsh chrome docker golang tmux zplug

zsh:
	sh ./init/zsh.sh

chrome:
	sh ./init/chrome.sh

docker:
	sh ./init/docker.sh

golang:
	sh ./init/golang.sh

tmux:
	sh ./init/tmux.sh

zplug:
	sh ./init/zplug.sh