# alias
alias cat='bat'
alias ls='exa'
alias ll='ls -alF'
alias la='ls -a'
alias lt='ls -T'
alias lsd='exa -D'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias a='alias'
alias b='brew'
alias c='pbcopy'
alias d='docker'
alias e='vim'
alias f='fd'
alias h='histroy'
alias i='docker ps -a'
alias j='jobs'
alias k='kubectl'
alias l='ls -alF'
alias m='make'
alias n='npm'
alias o='open'
alias p='pwd'
alias q='exit'
#alias r=''
alias s='ssh'
alias t='tmux'
alias u='cd ..'
alias v='vim'
#alias x=''
alias y='yarn'
alias z='zsh'
# editor
alias edit='code'
# NeoVim
alias vim=nvim
# fzf
alias pj='cd $(ghq list -p | fzf)'
alias gopn='hub browse $(ghq list | peco | cut -d "/" -f 2,3,4)'
alias dotfiles="cd ~/dotfiles"
alias dc='docker-compose'
alias allps='ps aux'
alias rezsh="exec $SHELL -l"
alias pwdc='pwd | tr -d "\n" | pbcopy'
alias -s gz='tar -xzvf'